### ISSUE TITLE
在vue中，什么情况下使用computed，什么情况下使用watch？为什么？

### ISSUE THREAD

**Issue by stovd** [wuweijia/blog#61]

**Comment by wuweijia** [comment]
几天了都没人回答，我简单说一下我的理解

1.  watch的场景：一个数据影响多个数据
    computed的场景：一个数据受多个数据影响
2. 计算属性（computed）在依赖数据项的初始化时就会执行，但watch在watch对象初始化时并不会执行

**Comment by wuweijia** [comment]
还有一个就是computed 机智的缓存策略

**Comment by Caaalabash** [comment]
从语义上来说呢:

+ `watch`: 观察一个值的变动, 触发一个回调

+ `computed`: 根据一个值计算出另一个值~

其他的特点有

+ `computed`有缓存, 默认只有`getter`, 但可以自己添加`setter`

+ `watch`有`deep`以及`immediate`选项

**Comment by wuweijia** [comment]
时隔一年终于来补答案了 😢
https://github.com/wuweijia/blog/issues/88
